name: build-gha-vcpkg
on:
  workflow_dispatch:

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15] # ubuntu-24.04, windows-2022]
        include:
          # - os: ubuntu-24.04
          #   workflow: ubuntu-ci
          # - os: windows-2022
          #   workflow: windows-ci
          - os: macos-15
            workflow: macos-ci
    permissions:
      packages: write
      contents: read
    env:
      VCPKG_EXECUTABLE: ${{ github.workspace }}/vcpkg/vcpkg
      NUGET_FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite"

    steps:
      - name: Install system dependencies and tools
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            pkg-config            \
            autoconf              \
            autoconf-archive      \
            automake              \
            libtool               \
            wayland-protocols     \
            libwayland-dev        \
            libwayland-client0    \
            libxtst-dev           \
            libxinerama-dev       \
            libxcursor-dev        \
            '^libxcb.*-dev'       \
            libx11-xcb-dev        \
            libgl1-mesa-dev       \
            libxrender-dev        \
            libxi-dev             \
            libxkbcommon-dev      \
            libxkbcommon-x11-dev  \
            libsystemd-dev        \
            libarchive-dev        \
            libxrandr-dev         \
            libltdl-dev
          sudo apt-get -y install mono-complete

      - name: Setup .NET SDK (macOS)
        if: runner.os == 'macOS'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - uses: lukka/get-cmake@latest

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Add NuGet sources (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          mono `${{ env.VCPKG_EXECUTABLE }} fetch nuget | tail -n 1` \
            sources add \
            -Source "${{ env.NUGET_FEED_URL }}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{ github.repository_owner }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}"
          mono `${{ env.VCPKG_EXECUTABLE }} fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "${{ env.NUGET_FEED_URL }}"

      - name: Add NuGet sources (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $nugetPath = & $env:VCPKG_EXECUTABLE fetch nuget | Select-Object -Last 1
          Write-Host "NuGet path: $nugetPath"
          & $nugetPath sources add `
            -Source "$env:NUGET_FEED_URL" `
            -Name "GitHubPackages" `
            -Username "${{ github.repository_owner }}" `
            -Password "${{ secrets.GITHUB_TOKEN }}" `
            -ConfigFile "$env:APPDATA\NuGet\NuGet.config"
          & $nugetPath setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "$env:NUGET_FEED_URL"

      - name: Add NuGet sources (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew install mono
          NUGET_EXE=$(${{ env.VCPKG_EXECUTABLE }} fetch nuget | tail -n 1)
          mono "$NUGET_EXE" sources add \
            -Source "${{ env.NUGET_FEED_URL }}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{ github.repository_owner }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}" \
            -Verbosity detailed
          mono "$NUGET_EXE" setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "${{ env.NUGET_FEED_URL }}" \
            -Verbosity detailed

      - name: Build, test and pack using CMake
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: ${{ matrix.workflow }}
