name: build-gha-vcpkg
on:
  workflow_dispatch:

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022] # , macos-15
        include:
          - os: ubuntu-24.04
            preset: linux-vcpkg-release
          - os: windows-2022
            preset: windows-vcpkg-release
    env:
      _VCPKG_: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      VCPKG_BINARY_SOURCES: 'default,rw'

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Update APT and install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            pkg-config            \
            autoconf              \
            autoconf-archive      \
            automake              \
            libtool               \
            wayland-protocols     \
            libwayland-dev        \
            libwayland-client0    \
            libxtst-dev           \
            libxinerama-dev       \
            libxcursor-dev        \
            '^libxcb.*-dev'       \
            libx11-xcb-dev        \
            libgl1-mesa-dev       \
            libxrender-dev        \
            libxi-dev             \
            libxkbcommon-dev      \
            libxkbcommon-x11-dev  \
            libsystemd-dev        \
            libarchive-dev        \
            libxrandr-dev         \
            libltdl-dev

      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Create directory '${{ env.VCPKG_DEFAULT_BINARY_CACHE }}'"
        run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
        shell: bash

      - uses: lukka/get-cmake@latest

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Set up binary cache
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ runner.os }}-${{ hashFiles('.git/modules/vcpkg/HEAD') }}-${{ hashFiles('vcpkg*.json') }}

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Restore from cache the dependencies and generate project files
        run: |
          cmake --preset ${{ matrix.preset }}

      - name: Build (Release configuration)
        run: |
          cmake --build --preset ${{ matrix.preset }}

      # - name: Test (Release configuration)
      #   run: |
      #     ctest --preset test-release
