name: CI/CD Linux
on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    container:
      image: ghcr.io/wolodyx/numgeom-ci-linux-system:latest
      options: '--user 1001:1001'
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build, test and package
        run: cmake --workflow --preset ci-linux-system

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          working_directory: bld/linux-system-release
          files: '*.deb'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
