name: CI/CD Linux
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    container:
      image: ghcr.io/wolodyx/numgeom-ci-linux-system:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Build
        run: cmake --workflow --preset ci-linux-system

      - name: Build package
        run: cmake --build --preset linux-system-release --target deb

      - uses: actions/upload-artifact@v4
        with:
          path: bld/linux-system-release/build/packages/deb/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
