name: CI/CD pipeline for linux-docker-system configuration
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read

    container:
      image: ghcr.io/wolodyx/numgeom-ci-linux-system:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Build
        run: cmake --workflow --preset ci-linux-system
