name: Deploy SDK

on:
  workflow_dispatch:

jobs:
  sdk-windows:
    name: SDK (Windows)
    runs-on: windows-2022
    env:
      VCPKG_BINARY_SOURCES: clear;x-aws,s3://${{ secrets.YC_BUCKET_NAME }}/vcpkg-cache/,readwrite
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL: https://storage.yandexcloud.net
      AWS_DEFAULT_BUCKET: ${{ secrets.YC_BUCKET_NAME }}
      AWS_DEFAULT_REGION: ru-central1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Initialize vcpkg submodule
        run: git submodule update --init

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat -disableMetrics

      - name: Install dependencies
        run: .\vcpkg\vcpkg.exe install

      - name: Export installed packages to ZIP archive
        run: .\vcpkg\vcpkg.exe export --zip --output-dir=.

      - name: Rename archive with triplet
        shell: pwsh
        run: |
          $archive = Get-Item vcpkg-export-*.zip
          $triplet="x64-windows"
          $newname = $archive.Name -replace 'vcpkg-export', "vcpkg-export-$triplet"
          Rename-Item -Path $archive.FullName -NewName $newname

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v7
        with:
          name: sdk-windows
          path: vcpkg-export-*.zip
          if-no-files-found: error

  sdk-ubuntu:
    name: SDK (Ubuntu)
    runs-on: ubuntu-latest
    env:
      VCPKG_BINARY_SOURCES: "clear;x-aws,s3://${{ secrets.YC_BUCKET_NAME }}/vcpkg-cache/,readwrite"
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL: "https://storage.yandexcloud.net"
      AWS_DEFAULT_BUCKET: ${{ secrets.YC_BUCKET_NAME }}
      AWS_DEFAULT_REGION: "ru-central1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Initialize vcpkg submodule
        run: git submodule update --init

      - name: Bootstrap vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Install system dependencies and tools
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            pkg-config            \
            autoconf              \
            autoconf-archive      \
            automake              \
            libtool               \
            wayland-protocols     \
            libwayland-dev        \
            libwayland-client0    \
            libxtst-dev           \
            libxinerama-dev       \
            libxcursor-dev        \
            '^libxcb.*-dev'       \
            libx11-xcb-dev        \
            libgl1-mesa-dev       \
            libxrender-dev        \
            libxi-dev             \
            libxkbcommon-dev      \
            libxkbcommon-x11-dev  \
            libegl1-mesa-dev      \
            libglu1-mesa-dev      \
            libsm-dev             \
            libsystemd-dev        \
            libarchive-dev        \
            libxrandr-dev         \
            libltdl-dev

      - name: Install dependencies
        run: ./vcpkg/vcpkg install

      - name: Export installed packages to ZIP archive
        run: ./vcpkg/vcpkg export --zip --output-dir=.

      - name: Rename archive with triplet
        shell: bash
        run: |
          archive=$(ls vcpkg-export-*.zip)
          triplet="x64-linux-dynamic"
          newname="${archive/vcpkg-export/vcpkg-export-${triplet}}"
          mv "$archive" "$newname"

      - name: Upload SDK artifact
        uses: actions/upload-artifact@v7
        with:
          name: sdk-ubuntu
          path: vcpkg-export-*.zip
          if-no-files-found: error
