name: Windows Build
on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: ['v*']
    paths-ignore:
      - '.devcontainer'
      - '.github/**'
      - '!.github/workflows/windows.yml'
      - '.vscode'
      - 'docs/**'
      - 'vcpkg/**'
      - '**.md'
  pull_request:
    types: [opened]
    paths-ignore:
      - '.devcontainer'
      - '.github/**'
      - '!.github/workflows/windows.yml'
      - '.vscode'
      - 'docs/**'
      - 'vcpkg/**'
      - '**.md'

jobs:
  build-system:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools
          vulkan-use-cache: true
      - name: Install Boost
        uses: MarkusJx/install-boost@v2
        id:
          install-boost
        with:
          boost_version: 1.89.0
          platform_version: 2022
          toolset: msvc
          link: static
          cache: true
      - name: Install Pyhton
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          cache: true
      - name: Build, test and package
        run: cmake --workflow --preset ci-windows-system
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

  build-with-vcpkg:
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: clear;x-aws,s3://${{ secrets.YC_BUCKET_NAME }}/vcpkg-cache/,readwrite
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL: https://storage.yandexcloud.net
      AWS_DEFAULT_BUCKET: ${{ secrets.YC_BUCKET_NAME }}
      AWS_DEFAULT_REGION: ru-central1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - uses: lukka/get-cmake@latest
      - name: Install NSIS
        uses: negrutiu/nsis-install@v2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install WiX Toolset v4
        run: |
          dotnet tool install --global wix --version 4.0.4
          wix extension add --global WixToolset.UI.wixext
      - name: Build, test and package
        run: cmake --workflow --preset ci-windows-vcpkg
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          working_directory: bld/windows-vcpkg
          files: |
            numgeom-*-win64.exe
            numgeom-*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
